arch:
  H_cycles: 3
  H_layers: 0
  L_cycles: 4
  L_layers: 2
  expansion: 4
  forward_dtype: bfloat16
  halt_exploration_prob: 0.1
  halt_max_steps: 16
  hidden_size: 256
  loss:
    loss_type: stablemax_cross_entropy
    name: losses@ACTLossHead
  mlp_t: false
  name: recursive_reasoning.trm@TinyRecursiveReasoningModel_ACTV1
  no_ACT_continue: true
  num_heads: 8
  pos_encodings: rope
  puzzle_emb_len: 8
  puzzle_emb_ndim: 256
beta1: 0.9
beta2: 0.95
checkpoint_every_eval: true
checkpoint_path: checkpoints/Dsl_trm_55modules_1m_full-ACT-torch/dsl_55mods_v2_phase2_baseline
data_paths:
- data/dsl_trm_55modules_1m_phase2
data_paths_test: []
ema: true
ema_rate: 0.999
epochs: 100
eval_interval: 10
eval_save_outputs: []
evaluators: []
freeze_weights: false
global_batch_size: 768
load_checkpoint: null
lr: 0.0001
lr_min_ratio: 0.1
lr_warmup_steps: 1000
min_eval_interval: 0
project_name: Dsl_trm_55modules_1m_full-ACT-torch
puzzle_emb_lr: 0.01
puzzle_emb_weight_decay: 0.1
run_name: dsl_55mods_v2_phase2_baseline
seed: 42
weight_decay: 0.1
