arch:
  H_cycles: 3
  H_layers: 0
  L_cycles: 6
  L_layers: 2
  expansion: 4
  forward_dtype: bfloat16
  halt_exploration_prob: 0.1
  halt_max_steps: 16
  hidden_size: 512
  loss:
    loss_type: stablemax_cross_entropy
    name: losses@ACTLossHead
  mlp_t: false
  name: recursive_reasoning.trm@TinyRecursiveReasoningModel_ACTV1
  no_ACT_continue: true
  num_heads: 8
  pos_encodings: rope
  puzzle_emb_len: 8
  puzzle_emb_ndim: 512
beta1: 0.9
beta2: 0.95
checkpoint_every_eval: true
checkpoint_path: checkpoints/English_dsl_compiler_1m_trm-ACT-torch/TinyRecursiveReasoningModel_ACTV1
  raspberry-crocodile
data_paths:
- data/english_dsl_compiler_1m_trm
data_paths_test: []
ema: true
ema_rate: 0.999
epochs: 50
eval_interval: 10
eval_save_outputs: []
evaluators: []
freeze_weights: false
global_batch_size: 768
load_checkpoint: /workspace/manas/checkpoints/English_dsl_compiler_1m_trm-ACT-torch/TinyRecursiveReasoningModel_ACTV1
  perfect-turtle/step_61870
lr: 0.0001
lr_min_ratio: 0.1
lr_warmup_steps: 1000
min_eval_interval: 0
project_name: English_dsl_compiler_1m_trm-ACT-torch
puzzle_emb_lr: 0.01
puzzle_emb_weight_decay: 0.1
run_name: TinyRecursiveReasoningModel_ACTV1 raspberry-crocodile
seed: 42
weight_decay: 0.1
